# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0002_event_public_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['start']},
        ),
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
    ]
