# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0006_auto_20160423_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('logo', models.ImageField(upload_to='partners')),
                ('events', models.ManyToManyField(related_name='partners', to='publicsite.Event')),
            ],
        ),
    ]
