# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0007_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(null=True, upload_to='speakers'),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
