# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0008_auto_20160816_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='latitude',
            new_name='place_latitude',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='longitude',
            new_name='place_longitude',
        ),
        migrations.AddField(
            model_name='place',
            name='center_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='center_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='zoom',
            field=models.IntegerField(null=True),
        ),
    ]
