# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0009_auto_20160827_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 31, 9, 51, 1, 155715)),
            preserve_default=False,
        ),
    ]
