# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0010_visitor_registered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_center_latitude', models.FloatField(null=True)),
                ('map_center_longitude', models.FloatField(null=True)),
                ('map_zoom', models.IntegerField(null=True)),
                ('start_publication_date', models.DateTimeField(null=True)),
                ('stop_publication_date', models.DateTimeField(null=True)),
                ('stop_registration_date', models.DateTimeField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='publicsite.Event')),
            ],
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_longitude',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='center_latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='center_longitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='zoom',
        ),
    ]
